HouseRentingSystem/Controllers/HomeController.cs
using HouseRentingSystem.Core.Contracts;
using HouseRentingSystem.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace HouseRentingSystem.Controllers
{
    public class HomeController : Controller
    {
        private readonly IHouseService _houseService;

        public HomeController(IHouseService houseService)
        {
            _houseService = houseService;
        }

        public async Task<IActionResult> Index()
        {
            var model = await _houseService.GetLastThreeHouses();

            return View(model); 
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HouseRentingSystem/Controllers/HouseController.cs
using HouseRentingSystem.Core.Contracts;
using HouseRentingSystem.Core.Models.House;
using HouseRentingSystem.Extensions;
using HouseRentingSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HouseRentingSystem.Controllers
{
    [Authorize]
    public class HouseController : Controller
    {
        private readonly IHouseService _houseService;
        private readonly IAgentService _agentService;

        public HouseController(
            IHouseService houseService, 
            IAgentService agentService)
        {
            _houseService = houseService;
            _agentService = agentService;
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> All([FromQuery]AllHousesQueryModel queryModel)
        {
            var result = await _houseService.All(
                queryModel.Category,
                queryModel.SearchTerm,
                queryModel.Sorting,
                queryModel.CurrentPage,
                AllHousesQueryModel.HousesPerPage);

            queryModel.TotalHousesCount = result.TotalHousesCount;
            queryModel.Categories = await _houseService.AllCategoryNames();
            queryModel.Houses = result.Houses;

            return View(queryModel);
        }

        [HttpGet]
        public async Task<IActionResult> Mine()
        {
            IEnumerable<HouseServiceModel> myHouses;

            var userId = User.Id();

            if(await _agentService.ExistsByIdAsync(userId))
            {
                int agentId = await _agentService.GetAgentIdAsync(userId);
                myHouses = await _houseService.AllHousesByAgentId(agentId);
            }
            else
            {
                myHouses = await _houseService.AllHousesByUserId(userId);
            }

            return View(myHouses);
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            if((await _houseService.Exists(id)) == false)
            {
                return RedirectToAction(nameof(All));
            }

            var model = await _houseService.HouseDetailsById(id);

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            if (await _agentService.ExistsByIdAsync(User.Id()) == false)
            {
                return RedirectToAction(nameof(AgentController.Become), "Agent");
            }

            var model = new HouseModel()
            {
                HouseCategories = await _houseService.AllCategories()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(HouseModel model)
        {
            if (await _agentService.ExistsByIdAsync(User.Id()) == false)
            {
                return RedirectToAction(nameof(AgentController.Become), "Agent");
            }

            if ((await _houseService.CategoryExists(model.CategoryId)) == false)
            {
                ModelState.AddModelError(nameof(model.CategoryId), "Category does not exists!");
            }

            if (!ModelState.IsValid)
            {
                model.HouseCategories = await _houseService.AllCategories();    

                return View(model); 
            }

            int agentId = await _agentService.GetAgentIdAsync(User.Id());

            int id = await _houseService.Create(model, agentId);

            return RedirectToAction(nameof(Details), new { id });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if((await _houseService.Exists(id))==false)
            {
                return RedirectToAction(nameof(All));
            }

            if((await _houseService.HasAgentWithId(id, User.Id()))== false)
            {
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
			}

            var house = await _houseService.HouseDetailsById(id);
            var categoryId = await _houseService.GetHouseCategoryId(id);

			var model = new HouseModel()
            {
                Id = house.Id,
                Address = house.Address,
                PricePerMonth = house.PricePerMonth,
                Description = house.Description,
                Title = house.Title,
                HouseCategories = await _houseService.AllCategories(),
                ImageUrl = house.ImageUrl,
                CategoryId = categoryId
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, HouseModel model)
        {
            if(id != model.Id)
            {
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });

            }
            if ((await _houseService.Exists(model.Id)) == false)
			{
				model.HouseCategories = await _houseService.AllCategories();
				ModelState.AddModelError("", "House does not exist!");
				return View(model);
			}

			if ((await _houseService.HasAgentWithId(model.Id, User.Id())) == false)
			{
				return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
			}

            if ((await _houseService.CategoryExists(model.CategoryId)) == false)
            {
				model.HouseCategories = await _houseService.AllCategories();
				ModelState.AddModelError(nameof(model.CategoryId), "Category does not exist!");
				return View(model);
			}

			if (!ModelState.IsValid)
			{
				model.HouseCategories = await _houseService.AllCategories();
				return View(model);
			}
			await _houseService.Edit(model.Id, model);
			return RedirectToAction(nameof(Details), new { model.Id});
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if ((await _houseService.Exists(id)) == false)
            {
                return RedirectToAction(nameof(All));
            }
            if ((await _houseService.HasAgentWithId(id, User.Id())) == false)
            {
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
            }

            var house = await _houseService.HouseDetailsById(id);

            var model = new HouseDetailsViewModel()
            {
                Address = house.Address,
                Title = house.Title,
                ImageUrl = house.ImageUrl
            };

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int id, HouseDetailsViewModel model)
        {
            if ((await _houseService.Exists(id)) == false)
            {
                return RedirectToAction(nameof(All));
            }

            if ((await _houseService.HasAgentWithId(id, User.Id())) == false)
            {
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
            }

            await _houseService.Delete(id);

            return RedirectToAction(nameof(All));
        }

        [HttpPost]
        public async Task<IActionResult> Rent(int id)
        {
            if ((await _houseService.Exists(id)) == false)
            {
                return RedirectToAction(nameof(All));
            }

            if (await _agentService.ExistsByIdAsync(User.Id()))
            {
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
            }
            if(await _houseService.IsRented(id))
            {
                return RedirectToAction(nameof(All));
            }
            await _houseService.Rent(id, User.Id());

            return RedirectToAction(nameof(Mine));
        }

        [HttpPost]
        public async Task<IActionResult> Leave(int id)
        {
            if ((await _houseService.Exists(id)) == false || 
                (await _houseService.IsRented(id)) == false)
            {
                return RedirectToAction(nameof(All));
            }

            if (await _houseService.IsRentedByUserWithId(id, User.Id()) == false)
            {
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
            }

            await _houseService.Leave(id);

            return RedirectToAction(nameof(Mine));
        }
    }
}

HouseRentingSystem/Views/Home/Index.cshtml
@model IEnumerable<HouseHomeModel>

@{
	ViewData["Title"] = "Home Page";
	bool first = true;
}

@if (Model.Count() == 0)
{
	<div class="mt-4 p-5 bg-light">
		<h1 class="display-4 mb-5">Welcome to HOUSE 4 RENT <br> - the best place for renting houses!</h1>
		<p class="lead">
			There are no houses in the system currently available so why don't you just add one?
		</p>
		<hr class="my-4">
		<p class="lead">
			@if (this.User?.Identity != null && this.User.Identity.IsAuthenticated)
			{
				<a asp-controller="House" asp-action="Add" class="btn btn-primary btn-lg" role="button">Add House</a>
			}
		</p>
	</div>
}

<div class="mb-5"></div>
<div class="container align-content-center w-75">
	<div id="carouselExampleControls" class="container-md carousel slide" data-bs-ride="carousel">
		<div class="carousel-inner">
			@foreach (var house in Model)
			{
				<div class="carousel-item @(first ? "active" : string.Empty)">
					<img class="d-block w-100 h-75 container-md" src="@house.ImageUrl" alt="@house.Title">
					<div class="carousel-caption d-none d-md-block">
						<h5>
							<a class="btn btn-primary" asp-controller="House" asp-action="Details"
						   asp-route-id="@house.Id"> @house.Title</a>
						</h5>
					</div>
				</div>
				first = false;
			}
		</div>
		<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
			<span class="carousel-control-prev-icon" aria-hidden="true"></span>
			<span class="visually-hidden">Previous</span>
		</button>
		<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
			<span class="carousel-control-next-icon" aria-hidden="true"></span>
			<span class="visually-hidden">Next</span>
		</button>
	</div>
</div>
<div class="mb-5"></div>

<div class="row">
	<div class="col-12 text-center">
		<button class="btn btn-outline-primary" id="statistics-button">Show Statistics</button>
	</div>
</div>

<div class="mt-4 p-5 bg-primary bg-opacity-50 d-none" id="statistics">
	<div class="row">
		<h2 class="col-md-6 text-center" id="total-houses"></h2>
		<h2 class="col-md-6 text-center" id="total-rents"></h2>
	</div>
</div>


@section Scripts {
	<script>
		$('#statistics-button').on('click', ev => {
			$.get('https://localhost:7169/api/statistics', (data) => {
				$('#total-houses').text(data.totalHouses + " Houses");
				$('#total-rents').text(data.totalRents + " Rents");
				$('#statistics').removeClass('d-none');
				$('#statistics-button').hide();
			});
		});
	</script>
    }